### ISSUE TITLE
新增author based的动态加载

### ISSUE THREAD

**Issue by Yikun** [opensourceways/whitebox#2]
```yaml
users:
- name: 'Yikun Jiang'
  gitee_id: 'yikunkero'
  github_id: 'Yikun'
  repos:
  - https://github.com/apache/spark
  - https://github.com/yikun/hub-mirror-action
  - https://github.com/yikun/repoinsight
  - https://gitee.com/opensourceway/om-bigdata
- name: 'Jun Zhong'
  gitee_id: 'zhongjun2'
  github_id: 'zhongjun2'
  repos:
  - https://gitee.com/opensourceway/om-collections
  - https://gitee.com/opensourceway/om-webserver
  - https://github.com/opensourceways/infra-common
  - https://gitee.com/opensourceway/om-bigdata
```
[1] https://github.com/opensourceways/whitebox/blob/6704a0bd9adea1f2869b19a47dc1c326ce2cb827/data.yml
根据以上yml动态获取项目，并且根据`github_id`和`gitee_id`获取对应仓库的链接。

任务分解：
### 1. 加载commits支持author过滤
指定仅过滤specific author的commits入库
多author的commits查询：
git log --author="zhongjun2" --author "Yikun"

### 2. 动态加载项目
基础的数据结构可以用hash拉链的方式，projects的key可以保证项目去重，对应author直接append到value：
```python
import collections

projects =collections.defaultdict(list)

def load_projects():
    with open("./data.yml") as f:
        x = yaml.load(f, Loader=yaml.FullLoader)
        users = x.get("users")
        for user in users:
            repos = user.get('repos', [])
            for repo in repos:
                gitee_user = user.get('gitee_id', 'Unknow')
                github_user = user.get('github_id', 'Unknow')
                real_user = gitee_user if 'gitee.com' in repo else github_user
                projects[repo].append(real_user)
```
遍历每个项目，clone，git log查询对应author的commits插入

### 4. （低优先级，Grafana也可处理）新增拼接commits_url列
需要根据commit id拼接为：
https://gitee.com/opensourceway/om-bigdata/commit/05b85d98234fc94d52b572af9c164c982226706b
